2013-07-27 13:21:09,714 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 101, in get_response
    request.path_info)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 298, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 328, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 323, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\frespo\urls.py", line 5, in <module>
    from core.forms import RegistrationForm
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\core\forms.py", line 4, in <module>
    from registration.forms import RegistrationForm as _RegistrationForm
ImportError: No module named registration.forms
2013-07-27 13:21:12,206 [ERROR] django.request: Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 89, in get_response
    response = middleware_method(request)
  File "C:\Python27\lib\site-packages\django\middleware\common.py", line 67, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 531, in is_valid_path
    resolve(path, urlconf)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 420, in resolve
    return get_resolver(urlconf).resolve(path)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 298, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 328, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 323, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\frespo\urls.py", line 5, in <module>
    from core.forms import RegistrationForm
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\core\forms.py", line 4, in <module>
    from registration.forms import RegistrationForm as _RegistrationForm
ImportError: No module named registration.forms
2013-07-27 13:21:16,096 [ERROR] django.request: Internal Server Error: /sandbox
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 89, in get_response
    response = middleware_method(request)
  File "C:\Python27\lib\site-packages\django\middleware\common.py", line 67, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 531, in is_valid_path
    resolve(path, urlconf)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 420, in resolve
    return get_resolver(urlconf).resolve(path)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 298, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 328, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 323, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\frespo\urls.py", line 5, in <module>
    from core.forms import RegistrationForm
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\core\forms.py", line 4, in <module>
    from registration.forms import RegistrationForm as _RegistrationForm
ImportError: No module named registration.forms
2013-07-27 13:21:18,203 [ERROR] django.request: Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 89, in get_response
    response = middleware_method(request)
  File "C:\Python27\lib\site-packages\django\middleware\common.py", line 67, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 531, in is_valid_path
    resolve(path, urlconf)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 420, in resolve
    return get_resolver(urlconf).resolve(path)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 298, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 328, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 323, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\frespo\urls.py", line 5, in <module>
    from core.forms import RegistrationForm
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\core\forms.py", line 4, in <module>
    from registration.forms import RegistrationForm as _RegistrationForm
ImportError: No module named registration.forms
2013-07-27 13:22:12,634 [ERROR] django.request: Internal Server Error: /sandbox
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 89, in get_response
    response = middleware_method(request)
  File "C:\Python27\lib\site-packages\django\middleware\common.py", line 67, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 531, in is_valid_path
    resolve(path, urlconf)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 420, in resolve
    return get_resolver(urlconf).resolve(path)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 298, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 328, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 323, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\frespo\urls.py", line 28
    )
    ^
SyntaxError: invalid syntax
2013-07-27 13:22:14,732 [ERROR] django.request: Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 89, in get_response
    response = middleware_method(request)
  File "C:\Python27\lib\site-packages\django\middleware\common.py", line 67, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 531, in is_valid_path
    resolve(path, urlconf)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 420, in resolve
    return get_resolver(urlconf).resolve(path)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 298, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 328, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 323, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\frespo\urls.py", line 28
    )
    ^
SyntaxError: invalid syntax
2013-07-27 13:22:28,453 [ERROR] django.request: Internal Server Error: /sandbox
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 89, in get_response
    response = middleware_method(request)
  File "C:\Python27\lib\site-packages\django\middleware\common.py", line 67, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 531, in is_valid_path
    resolve(path, urlconf)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 420, in resolve
    return get_resolver(urlconf).resolve(path)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 298, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 328, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 323, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\frespo\urls.py", line 5, in <module>
    from core.forms import RegistrationForm
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\core\forms.py", line 4, in <module>
    from registration.forms import RegistrationForm as _RegistrationForm
ImportError: No module named registration.forms
2013-07-27 13:22:30,568 [ERROR] django.request: Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 89, in get_response
    response = middleware_method(request)
  File "C:\Python27\lib\site-packages\django\middleware\common.py", line 67, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 531, in is_valid_path
    resolve(path, urlconf)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 420, in resolve
    return get_resolver(urlconf).resolve(path)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 298, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 328, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 323, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\frespo\urls.py", line 5, in <module>
    from core.forms import RegistrationForm
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\core\forms.py", line 4, in <module>
    from registration.forms import RegistrationForm as _RegistrationForm
ImportError: No module named registration.forms
2013-07-27 13:23:19,198 [ERROR] django.request: Internal Server Error: /sandbox/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\simple.py", line 27, in direct_to_template
    t = loader.get_template(template)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: sandbox/home.html
2013-07-27 13:23:21,311 [ERROR] django.request: Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 150, in get_response
    response = callback(request, **param_dict)
  File "C:\Python27\lib\site-packages\django\utils\decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\defaults.py", line 20, in page_not_found
    t = loader.get_template(template_name) # You need to create a 404.html template.
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: 404.html
2013-08-10 20:12:35,323 [ERROR] django.request: Internal Server Error: /sandbox/issue_page
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\simple.py", line 27, in direct_to_template
    t = loader.get_template(template)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: sandbox/issue_page.html
2013-08-10 20:14:12,082 [ERROR] django.request: Internal Server Error: /sandbox/issue
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\simple.py", line 27, in direct_to_template
    t = loader.get_template(template)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: sandbox/issue_page.html
2013-08-10 20:14:46,436 [ERROR] django.request: Internal Server Error: /sandbox/issue_page
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\simple.py", line 27, in direct_to_template
    t = loader.get_template(template)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: sandbox/issue_page.html
2013-08-12 12:30:22,967 [ERROR] django.request: Internal Server Error: /sandbox/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\simple.py", line 28, in direct_to_template
    return HttpResponse(t.render(c), content_type=mimetype)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 823, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 74, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 134, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 42, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 48, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 153, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 214, in do_extends
    nodelist = parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 189, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 262, in do_include
    isolated_context=isolated_context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 145, in __init__
    t = get_template(template_path)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 134, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 42, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 45, in load_template
    source, display_name = self.load_template_source(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\filesystem.py", line 39, in load_template_source
    return (file.read().decode(settings.FILE_CHARSET), filepath)
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xbb in position 423: invalid start byte
2013-08-12 12:30:27,111 [ERROR] django.request: Internal Server Error: /sandbox/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\simple.py", line 28, in direct_to_template
    return HttpResponse(t.render(c), content_type=mimetype)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 823, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 74, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 134, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 42, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 48, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 153, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 214, in do_extends
    nodelist = parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 189, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 262, in do_include
    isolated_context=isolated_context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 145, in __init__
    t = get_template(template_path)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 134, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 42, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 45, in load_template
    source, display_name = self.load_template_source(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\filesystem.py", line 39, in load_template_source
    return (file.read().decode(settings.FILE_CHARSET), filepath)
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xbb in position 423: invalid start byte
2013-08-12 12:35:38,101 [ERROR] django.request: Internal Server Error: /sandbox/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\simple.py", line 28, in direct_to_template
    return HttpResponse(t.render(c), content_type=mimetype)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 823, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 74, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 134, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 42, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 48, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 153, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 214, in do_extends
    nodelist = parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 189, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 262, in do_include
    isolated_context=isolated_context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 145, in __init__
    t = get_template(template_path)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 134, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 42, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 45, in load_template
    source, display_name = self.load_template_source(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\filesystem.py", line 39, in load_template_source
    return (file.read().decode(settings.FILE_CHARSET), filepath)
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xbb in position 423: invalid start byte
2013-08-13 00:34:05,618 [ERROR] django.request: Internal Server Error: /sandbox/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\simple.py", line 27, in direct_to_template
    t = loader.get_template(template)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 134, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 42, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 48, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 153, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 214, in do_extends
    nodelist = parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 189, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 262, in do_include
    isolated_context=isolated_context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 145, in __init__
    t = get_template(template_path)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 134, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 42, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 45, in load_template
    source, display_name = self.load_template_source(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\filesystem.py", line 39, in load_template_source
    return (file.read().decode(settings.FILE_CHARSET), filepath)
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc9 in position 806: invalid continuation byte
2013-08-13 20:53:29,016 [ERROR] django.request: Internal Server Error: /sandbox/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\simple.py", line 27, in direct_to_template
    t = loader.get_template(template)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 134, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 42, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 45, in load_template
    source, display_name = self.load_template_source(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\filesystem.py", line 39, in load_template_source
    return (file.read().decode(settings.FILE_CHARSET), filepath)
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xab in position 892: invalid start byte
2013-08-13 20:54:39,940 [ERROR] django.request: Internal Server Error: /sandbox/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\simple.py", line 27, in direct_to_template
    t = loader.get_template(template)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 134, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 42, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 45, in load_template
    source, display_name = self.load_template_source(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\filesystem.py", line 39, in load_template_source
    return (file.read().decode(settings.FILE_CHARSET), filepath)
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xab in position 892: invalid start byte
2013-08-14 12:41:47,604 [ERROR] django.request: Internal Server Error: /sandbox/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\simple.py", line 27, in direct_to_template
    t = loader.get_template(template)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 134, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 42, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 45, in load_template
    source, display_name = self.load_template_source(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\filesystem.py", line 39, in load_template_source
    return (file.read().decode(settings.FILE_CHARSET), filepath)
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xab in position 892: invalid start byte
2013-08-14 12:42:36,836 [ERROR] django.request: Internal Server Error: /sandbox/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\simple.py", line 27, in direct_to_template
    t = loader.get_template(template)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 134, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 42, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 48, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 153, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 214, in do_extends
    nodelist = parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 189, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 262, in do_include
    isolated_context=isolated_context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 145, in __init__
    t = get_template(template_path)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 134, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 42, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 45, in load_template
    source, display_name = self.load_template_source(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\filesystem.py", line 39, in load_template_source
    return (file.read().decode(settings.FILE_CHARSET), filepath)
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc9 in position 967: invalid continuation byte
2013-08-14 12:43:21,732 [ERROR] django.request: Internal Server Error: /sandbox/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\simple.py", line 27, in direct_to_template
    t = loader.get_template(template)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 134, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 42, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 48, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 153, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 214, in do_extends
    nodelist = parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 189, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 262, in do_include
    isolated_context=isolated_context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 145, in __init__
    t = get_template(template_path)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 134, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 42, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 45, in load_template
    source, display_name = self.load_template_source(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\filesystem.py", line 39, in load_template_source
    return (file.read().decode(settings.FILE_CHARSET), filepath)
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc9 in position 967: invalid continuation byte
2013-08-14 12:46:51,545 [ERROR] django.request: Internal Server Error: /sandbox/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\simple.py", line 27, in direct_to_template
    t = loader.get_template(template)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 134, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 42, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 48, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 153, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 214, in do_extends
    nodelist = parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 189, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 262, in do_include
    isolated_context=isolated_context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 145, in __init__
    t = get_template(template_path)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 134, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 42, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 45, in load_template
    source, display_name = self.load_template_source(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\filesystem.py", line 39, in load_template_source
    return (file.read().decode(settings.FILE_CHARSET), filepath)
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc9 in position 571: invalid continuation byte
2013-08-14 12:47:25,194 [ERROR] django.request: Internal Server Error: /sandbox/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\simple.py", line 27, in direct_to_template
    t = loader.get_template(template)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 134, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 42, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 48, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 153, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 214, in do_extends
    nodelist = parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 189, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 262, in do_include
    isolated_context=isolated_context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 145, in __init__
    t = get_template(template_path)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 134, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 42, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 45, in load_template
    source, display_name = self.load_template_source(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\filesystem.py", line 39, in load_template_source
    return (file.read().decode(settings.FILE_CHARSET), filepath)
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc9 in position 548: invalid continuation byte
2013-08-14 13:06:01,923 [ERROR] django.request: Internal Server Error: /sandbox/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\simple.py", line 27, in direct_to_template
    t = loader.get_template(template)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 134, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 42, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 48, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 153, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 214, in do_extends
    nodelist = parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 189, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 262, in do_include
    isolated_context=isolated_context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 145, in __init__
    t = get_template(template_path)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 134, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 42, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 45, in load_template
    source, display_name = self.load_template_source(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\filesystem.py", line 39, in load_template_source
    return (file.read().decode(settings.FILE_CHARSET), filepath)
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc9 in position 967: invalid continuation byte
2013-08-14 13:06:30,618 [ERROR] django.request: Internal Server Error: /sandbox/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\simple.py", line 27, in direct_to_template
    t = loader.get_template(template)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 134, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 42, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 48, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 153, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 214, in do_extends
    nodelist = parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 189, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 262, in do_include
    isolated_context=isolated_context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 145, in __init__
    t = get_template(template_path)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 134, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 42, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 45, in load_template
    source, display_name = self.load_template_source(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\filesystem.py", line 39, in load_template_source
    return (file.read().decode(settings.FILE_CHARSET), filepath)
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc9 in position 967: invalid continuation byte
2013-08-14 13:06:31,520 [ERROR] django.request: Internal Server Error: /sandbox/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\simple.py", line 27, in direct_to_template
    t = loader.get_template(template)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 134, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 42, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 48, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 153, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 214, in do_extends
    nodelist = parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 189, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 267, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 262, in do_include
    isolated_context=isolated_context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 145, in __init__
    t = get_template(template_path)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 134, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 42, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 45, in load_template
    source, display_name = self.load_template_source(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\filesystem.py", line 39, in load_template_source
    return (file.read().decode(settings.FILE_CHARSET), filepath)
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc9 in position 967: invalid continuation byte
